quarkus:
  profile:
    parent: env
  log:
    level: INFO
    category:
      "task.service":
        level: DEBUG

  rest-client:
    auth-client:
      url: ${AUTH_CLIENT_URL}
      scope: jakarta.inject.Singleton
      connect-timeout: 5000
      read-timeout: 5000

  http:
    port: ${PORT}
    cors:
      ~: true
      origins: "http://localhost:5173"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "accept,authorization,content-type,x-requested-with"
      exposed-headers: "Content-Disposition"
      access-control-max-age: "24H"
      access-control-allow-credentials: true

kafka:
  bootstrap:
    servers: ${LOCAL_BROKER}

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

mp:
  messaging:
    outgoing:
      created:
        connector: smallrye-kafka
        topic: "item-created"
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer

url:
  redirect-url: ${CLIENT_REDIRECT_URL}
