quarkus:
  profile:
    parent: env
  log:
    level: INFO
    category:
      "task.service":
        level: DEBUG

#Registered REST clients
  rest-client:
    auth-client:
      url: ${AUTH_CLIENT_URL}
      scope: jakarta.inject.Singleton
      connect-timeout: 5000
      read-timeout: 5000
    task-client:
      url: ${TASK_CLIENT_URL}
      scope: jakarta.inject.Singleton
      connect-timeout: 5000
      read-timeout: 5000
    note-client:
      url: ${NOTE_CLIENT_URL}
      scope: jakarta.inject.Singleton
      connect-timeout: 5000
      read-timeout: 5000

#Service port and Cors
  http:
    port: ${PORT}
    cors:
      ~: true
      origins: "http://localhost:5173"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "accept,authorization,content-type,x-requested-with"
      exposed-headers: "Content-Disposition"
      access-control-max-age: "24H"
      access-control-allow-credentials: true

#Client application url
url:
  redirect-url: ${CLIENT_REDIRECT_URL}

#Kafka broker address
kafka:
  bootstrap:
    servers: ${LOCAL_BROKER}

#Log level for Kafka
logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

#Kafka channels and topics
mp:
  messaging:
    outgoing:
      created:
        connector: smallrye-kafka
        topic: "item-created"
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      updated:
        connector: smallrye-kafka
        topic: "item-updated"
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      deleted:
        connector: smallrye-kafka
        topic: "item-deleted"
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    incoming:
      completed:
        connector: smallrye-kafka
        topic: "feedback-completed"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      priority:
        connector: smallrye-kafka
        topic: "feedback-priority"
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
